import { z } from 'zod';
import { FURNITURE_KINDS } from '../src/lib/furnitureCatalog.ts';
import { FURNITURE_PARTS } from '../src/lib/furnitureParts.ts';
import { MATERIAL_CHOICES } from '../src/lib/materials.ts';

/**
 * Every distinct part key across the furniture catalog (a bed's "frame" vs
 * "bedding", a table's "top" vs "legs", …) — the same per-part vocabulary the
 * manual "Colours & materials" editor exposes (see `FURNITURE_PARTS` in
 * `src/lib/furnitureParts.ts`). Reused here rather than duplicated, so the
 * schema the model is constrained to can describe a colour/material per part.
 * A given piece only has a few of these keys (its own kind's parts); the rest
 * are simply never set for it.
 */
const ALL_PART_KEYS = Array.from(
  new Set(Object.values(FURNITURE_PARTS).flatMap((parts) => parts.map((p) => p.key))),
).sort();

const MATERIAL_IDS = MATERIAL_CHOICES.map((m) => m.value).join(', ');

/**
 * One optional field per known part key. Structured output requires every
 * object to declare `additionalProperties: false` (via `z.strictObject`), so
 * every part key across the whole catalog has to be enumerated up front —
 * the model only ever sets the handful that apply to a given piece's kind.
 */
function perPartSchema(field: 'colour' | 'material') {
  return z.strictObject(
    Object.fromEntries(
      ALL_PART_KEYS.map((key) => [
        key,
        z
          .string()
          .optional()
          .describe(
            field === 'colour'
              ? `Colour override for the "${key}" part, as #rrggbb.`
              : `Material for the "${key}" part. One of: ${MATERIAL_IDS}.`,
          ),
      ]),
    ),
  );
}

const aiColorsSchema = perPartSchema('colour');
const aiMaterialsSchema = perPartSchema('material');

/**
 * Response schema for AI-generated furnishing proposals. Sent as --json-schema
 * to Claude Code (structured output) and used to validate the response.
 * No numeric bounds here — structured output does not support them; the
 * geometry is checked in validate.ts instead.
 */
const aiFurnitureSchema = z.strictObject({
  kind: z
    .enum(FURNITURE_KINDS)
    .describe('Furniture type from the catalog; "box" for furniture without a dedicated type.'),
  name: z.string().describe('Short name, e.g. "Double bed" or "Desk".'),
  x: z.number().describe('Center of the footprint, x in meters in the room coordinate system.'),
  z: z.number().describe('Center of the footprint, z in meters in the room coordinate system.'),
  facing: z
    .strictObject({
      x: z.number(),
      z: z.number(),
    })
    .describe(
      "A point (x, z) in the room that the furniture's FRONT should point toward. The server " +
        "computes and snaps the rotation in that direction. Examples: a chair's front points " +
        "toward the table's center; a sofa's toward the center of the room or the TV; a " +
        "wardrobe's toward a point a bit out into the room (away from the wall). Never " +
        'specify the same point as x/z.',
    ),
  againstWall: z
    .boolean()
    .describe(
      "true if the furniture's back should stand flush against the nearest wall (wardrobe, " +
        'bookshelf, bed, sofa, TV bench). The server then snaps the furniture flush against ' +
        'the wall and turns the front out into the room. false for freestanding furniture ' +
        '(table, rug, chair).',
    ),
  size: z.strictObject({
    width: z.number().describe("Width in meters (along the furniture's own x-axis)."),
    depth: z.number().describe("Depth in meters (along the furniture's own z-axis)."),
    height: z.number().describe('Height in meters.'),
  }),
  elevation: z
    .number()
    .describe(
      'Underside above the floor in meters. 0 for furniture standing on the floor; > 0 for wall-mounted items (shelves etc.).',
    ),
  color: z.string().describe("Color as #rrggbb, harmonized with the proposal's palette."),
  colors: aiColorsSchema
    .optional()
    .describe(
      'Optional per-part colour overrides, keyed by part name (only the keys belonging to ' +
        "this piece's own kind apply — e.g. a bed has \"frame\"/\"bedding\", a table has " +
        '"top"/"legs"). Omit a part, or the whole field, to use the base colour above for it. ' +
        "Not required to vary every part — it's fine for most parts to just follow the base colour.",
    ),
  materials: aiMaterialsSchema
    .optional()
    .describe(
      'Optional per-part material/finish, keyed by part name (same per-kind keys as colors). ' +
        'Omit a part, or the whole field, to use a sensible default finish for it (e.g. a wood ' +
        "bed frame with fabric bedding). Not required to vary every part."
    ),
  reasoning: z
    .string()
    .describe('One sentence: why the furniture is placed exactly here (rule/principle).'),
});

// One furnishing proposal. Each is generated by its own model call (the proposals
// are produced in parallel, one direction per call — see server/index.ts), so the
// single-proposal schema below is what each call is constrained to. `proposalsSchema`
// wraps it back into the multi-proposal shape the rest of the pipeline expects.
const aiProposalSchema = z.strictObject({
  title: z.string().describe('Short title, e.g. "Light and airy".'),
  concept: z.string().describe("2–3 sentences about the proposal's core idea."),
  floorColor: z
    .string()
    .describe("Floor colour for this proposal as #rrggbb, part of the proposal's palette."),
  wallColor: z
    .string()
    .describe("Wall colour for this proposal as #rrggbb, part of the proposal's palette."),
  furniture: z.array(aiFurnitureSchema),
});

export const proposalsSchema = z.strictObject({
  proposals: z.array(aiProposalSchema).describe('Deliberately different proposals.'),
});

export type AiProposals = z.infer<typeof proposalsSchema>;
export type AiProposal = z.infer<typeof aiProposalSchema>;
export type AiFurniture = z.infer<typeof aiFurnitureSchema>;

/**
 * A furniture item after the server has resolved `facing`/`againstWall` into a
 * concrete `rotationY` (radians) and possibly adjusted x/z (flush against a wall).
 * This is the shape that gets validated and sent to the client — same fields as
 * the client's AiFurniture (src/lib/aiProposals.ts).
 */
export interface ResolvedFurniture {
  kind: AiFurniture['kind'];
  name: string;
  x: number;
  z: number;
  rotationY: number;
  size: AiFurniture['size'];
  elevation: number;
  color: string;
  /** Sanitized per-part colour overrides; see {@link ../src/lib/furnitureParts.normalizeColors}. */
  colors?: Record<string, string>;
  /** Sanitized per-part materials; see {@link ../src/lib/furnitureParts.normalizeMaterials}. */
  materials?: Record<string, string>;
  reasoning: string;
}

export interface ResolvedProposals {
  proposals: {
    title: string;
    concept: string;
    floorColor: string;
    wallColor: string;
    furniture: ResolvedFurniture[];
  }[];
}

// NOTE: the $schema key must be removed — with it, structured output is silently
// dropped. Each proposal is requested on its own, so the schema we constrain the
// model to is the single-proposal one.
const jsonSchema = z.toJSONSchema(proposalsSchema);
delete jsonSchema.$schema;
export const proposalsJsonSchema = jsonSchema;

const proposalJson = z.toJSONSchema(aiProposalSchema);
delete proposalJson.$schema;
export const proposalJsonSchema = proposalJson;
